collision_free_zones:
  # Top left big
  - id: 8
    zone:
      - [240, 90]
      - [237, 167]
      - [326, 170]
      - [325, 90]

  # Top crossing
  - id: 1
    zone:
      - [348, 149]
      - [348, 160]
      - [358, 160]
      - [358, 149]

  # Top right big
  - id: 2
    zone:
      - [377, 144]
      - [374, 230]
      - [428, 233]
      - [431, 144]

  # Right crossing
  - id: 3
    zone:
      - [382, 272]
      - [381, 287]
      - [395, 288]
      - [395, 272]

  # Bottom right big
  - id: 4
    zone:
      - [309, 301]
      - [309, 358]
      - [385, 360]
      - [386, 305]

  # Bottom crossing
  - id: 5
    zone:
      - [264, 304]
      - [264, 319]
      - [282, 319]
      - [282, 304]

  # Bottom left big
  - id: 6
    zone:
      - [188, 236]
      - [188, 308]
      - [255, 309]
      - [256, 236]

  # Left crossing
  - id: 7
    zone:
      - [232, 181]
      - [232, 202]
      - [249, 202]
      - [250, 181]

# BRUG KRUISPUNT NOORDZIJDE
  - id: 9
    zone:
      - [1327, 792]
      - [1326, 827]
      - [1376, 828]
      - [1377, 791]

# BRUG KRUISPUNT ZUIDZIJDE
  - id: 10
    zone:
      - [1246, 859]
      - [1246, 899]
      - [1295, 897]
      - [1295, 859]