directions:
  car:
    - id: 1
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [426, 245]
          front_sensor_position: [431, 247]
          back_sensor_position: [503, 282]
    - id: 2
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [421, 256]
          front_sensor_position: [427, 258]
          back_sensor_position: [498, 293]
        - id: 2
          approach_direction: east
          traffic_light_position: [416, 267]
          front_sensor_position: [422, 270]
          back_sensor_position: [494, 305]
    - id: 3
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [411, 279]
          front_sensor_position: [417, 282]
          back_sensor_position: [489, 316]
    - id: 4
      traffic_lights:
        - id: 1
          approach_direction: south
          traffic_light_position: [297, 342]
          front_sensor_position: [295, 347]
          back_sensor_position: [268, 402]
    - id: 5
      traffic_lights:
        - id: 1
          approach_direction: south
          traffic_light_position: [287, 338]
          front_sensor_position: [284, 343]
          back_sensor_position: [257, 397]
    - id: 6
      traffic_lights:
        - id: 1
          approach_direction: south
          traffic_light_position: [276, 333]
          front_sensor_position: [273, 339]
          back_sensor_position: [244, 391]
    - id: 7
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [204, 229]
          front_sensor_position: [196, 225]
          back_sensor_position: [147, 201]
    - id: 8
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [209, 218]
          front_sensor_position: [200, 213]
          back_sensor_position: [153, 190]
        - id: 2
          approach_direction: west
          traffic_light_position: [215, 206]
          front_sensor_position: [204, 201]
          back_sensor_position: [157, 178]
    - id: 9
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [220, 195]
          front_sensor_position: [209, 190]
          back_sensor_position: [162, 166]
    - id: 10
      traffic_lights:
        - id: 1
          approach_direction: north
          traffic_light_position: [332, 128]
          front_sensor_position: [335, 120]
          back_sensor_position: [359, 70]
    - id: 11
      traffic_lights:
        - id: 1
          approach_direction: north
          traffic_light_position: [343, 132]
          front_sensor_position: [347, 124]
          back_sensor_position: [371, 73]
    - id: 12
      traffic_lights:
        - id: 1
          approach_direction: north
          traffic_light_position: [353, 136]
          front_sensor_position: [357, 129]
          back_sensor_position: [381, 79]
    # BRIDGE
    - id: 41
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [1515, 976]
          front_sensor_position: [1527, 979]
    - id: 42
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [1333, 876]
          front_sensor_position: [1325, 869]



  pedestrian:
    - id: 31
      traffic_lights:
        - id: 1
          approach_direction: north
          traffic_light_position: [411, 227]
          front_sensor_position: [413, 224]
        - id: 2
          approach_direction: south
          traffic_light_position: [393, 280]
          front_sensor_position: [392, 282]
    - id: 32
      traffic_lights:
        - id: 1
          approach_direction: north
          traffic_light_position: [385, 281]
          front_sensor_position: [386, 278]
        - id: 2
          approach_direction: south
          traffic_light_position: [375, 312]
          front_sensor_position: [373, 315]
    - id: 33
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [316, 332]
          front_sensor_position: [319, 333]
        - id: 2
          approach_direction: west
          traffic_light_position: [274, 316]
          front_sensor_position: [271, 315]
    - id: 34
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [274, 311]
          front_sensor_position: [277, 312]
        - id: 2
          approach_direction: west
          traffic_light_position: [246, 303]
          front_sensor_position: [241, 300]
    - id: 35
      traffic_lights:
        - id: 1
          approach_direction: south
          traffic_light_position: [219, 247]
          front_sensor_position: [217, 249]
        - id: 2
          approach_direction: north
          traffic_light_position: [236, 193]
          front_sensor_position: [237, 190]
    - id: 36
      traffic_lights:
        - id: 1
          approach_direction: south
          traffic_light_position: [243, 193]
          front_sensor_position: [242, 195]
        - id: 2
          approach_direction: north
          traffic_light_position: [255, 160]
          front_sensor_position: [257, 157]
    - id: 37
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [314, 140]
          front_sensor_position: [310, 138]
        - id: 2
          approach_direction: east
          traffic_light_position: [355, 153]
          front_sensor_position: [357, 154]
    - id: 38
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [355, 158]
          front_sensor_position: [353, 157]
        - id: 2
          approach_direction: east
          traffic_light_position: [381, 166]
          front_sensor_position: [383, 167]
    - id: 51
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [1470, 922]
          front_sensor_position: [1473, 924]
    - id: 52
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [1411, 984]
          front_sensor_position: [1414, 987]
    - id: 53
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [1318, 909]
          front_sensor_position: [1314, 907]
    - id: 54
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [1373, 840]
          front_sensor_position: [1370, 836]

  bike:
    - id: 51
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [1464, 932]
          front_sensor_position: [1467, 934]
    - id: 52
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [1421, 975]
          front_sensor_position: [1425, 978]
    - id: 53
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [1327, 902]
          front_sensor_position: [1323, 898]
    - id: 54
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [1362, 848]
          front_sensor_position: [1357, 843]


  boat:
    - id: 71
      traffic_lights:
        - id: 1
          approach_direction: east
          traffic_light_position: [1482, 834]
          front_sensor_position: [1505, 816]
    - id: 72
      traffic_lights:
        - id: 1
          approach_direction: west
          traffic_light_position: [1301, 994]
          front_sensor_position: [1281, 1011]