route_components:
  - name: to_east
    path:
        - [384, 304]
        - [410, 317]
        - [676, 452]
        - [856, 542]
        - [887, 557]
        - [927, 578]
        - [954, 592]
        - [984, 611]
        - [1006, 626]
        - [1053, 656]
        - [1095, 685]
        - [1137, 719]
        - [1175, 747]
        - [1195, 762]
        - to_east_outer
  - name: to_south
    path:
        - [259, 311]
        - [248, 331]
        - [242, 348]
        - [229, 368]
        - [216, 391]
        - [197, 425]
        - [181, 444]
        - [159, 470]
        - [132, 497]
        - [87, 538]
  - name: to_north
    path:
        - [369, 157]
        - [378, 141]
        - [392, 120]
        - [411, 85]
        - [449, 5]
        - [460, -10]
  - name: to_east_outer
    path:
        - [1231, 792]
        - [1267, 822]
        - [1304, 852]
        - [1348, 890]
        - [1386, 923]
        - [1432, 963]
        - [1462, 994]
        - [1479, 1021]
        - [1485, 1048]
        - [1493, 1071]
        - [1508, 1086]
        - [1539, 1091]
        - [1567, 1097]
        - [1599, 1114]
        - [1635, 1140]
        - [1658, 1160]
        - [1730, 1217]
  - name: to_west
    path:
        - [242, 168]
        - [216, 155]
        - [182, 137]
        - [127, 110]
        - [16, 55]
        - [0, 47]
        - [-33, 17]








  - name: to_north_as_outer_pedestrian
    path:
        - [300, 119]
        - [313, 111]
        - [326, 99]
        - [335, 84]
        - [351, 44]
        - [371, 2]
        - [374, -5]

  - name: to_north_es_outer_pedestrian
    path:
        - [424, 177]
        - [421, 163]
        - [421, 149]
        - [423, 137]
        - [428, 123]
        - [437, 106]
        - [453, 77]
        - [464, 49]
        - [476, 24]
        - [491, -5]


  - name: from_north_as_outer_pedestrian
    path:
        - [370, -8]
        - [361, 12]
        - [346, 41]
        - [332, 72]
        - [325, 87]
        - [316, 98]
        - [305, 109]
        - [294, 113]
        - [284, 117]

  - name: from_north_es_outer_pedestrian
    path:
        - [479, -3]
        - [472, 16]
        - [465, 29]
        - [459, 44]
        - [449, 62]
        - [436, 92]
        - [427, 102]
        - [421, 119]
        - [415, 135]
        - [412, 148]
        - [411, 163]
        - [416, 178]

  - name: to_south_es_outer_pedestrian
    path:
        - [209, 288]
        - [198, 309]
        - [184, 336]
        - [175, 357]
        - [161, 388]
        - [146, 413]
        - [135, 428]
        - [124, 442]
        - [111, 456]
        - [99, 469]
        - [90, 479]
        - [62, 498]


  - name: to_south_as_outer_pedestrian
    path:
        - [345, 358]
        - [338, 370]
        - [330, 383]
        - [324, 392]
        - [322, 399]
        - [322, 406]
        - [322, 415]
        - [321, 422]
        - [317, 430]
        - [314, 436]
        - [310, 444]
        - [306, 450]
        - [301, 455]
        - [274, 480]
        - [245, 506]
        - [211, 537]
        - [189, 557]

  - name: from_south_es_outer_pedestrian
    path:
        - [71, 502]
        - [96, 480]
        - [120, 454]
        - [141, 430]
        - [155, 407]
        - [170, 379]
        - [185, 347]
        - [196, 328]
        - [203, 311]
        - [209, 297]
        - [217, 283]
        - [218, 276]

  - name: from_south_as_outer_pedestrian
    path:
        - [187, 562]
        - [216, 536]
        - [245, 509]
        - [264, 493]
        - [289, 471]
        - [307, 454]
        - [322, 441]
        - [327, 432]
        - [329, 420]
        - [329, 407]
        - [330, 398]
        - [338, 383]
        - [345, 367]
        - [353, 355]

  - name: to_west_as_outer_pedestrian
    path:
        - [215, 267]
        - [193, 256]
        - [152, 236]
        - [122, 220]
        - [73, 196]
        - [17, 168]
        - [-13, 153]

  - name: to_west_es_outer_pedestrian
    path:
        - [270, 119]
        - [249, 117]
        - [220, 104]
        - [181, 85]
        - [135, 62]
        - [65, 26]
        - [5, -3]


  - name: from_west_as_outer_pedestrian
    path:
        - [-1, 171]
        - [18, 177]
        - [36, 186]
        - [49, 193]
        - [76, 205]
        - [105, 223]
        - [127, 233]
        - [142, 240]
        - [163, 249]
        - [188, 261]
        - [204, 270]
        - [212, 274]

  - name: from_west_es_outer_pedestrian
    path:
        - [-2, 3]
        - [8, 7]
        - [92, 48]
        - [129, 66]
        - [174, 88]
        - [218, 110]
        - [244, 121]
        - [270, 126]
        - [275, 126]


  - name: to_east_as_outer_pedestrian
    path:
        - [432, 214]
        - [449, 225]
        - [479, 239]
        - [519, 259]
        - [561, 280]
        - [616, 309]
        - [707, 357]
        - [771, 393]
        - [893, 465]
        - [987, 522]
        - [1035, 557]
        - [1091, 596]
        - [1140, 634]
        - [1217, 696]
        - [1268, 740]
        - [1309, 778]
        - [1334, 802]
        - variations:
            - usage_percentage: 50
              path:
                  - [1342, 799]
                  - [1354, 790]
                  - [1375, 773]
                  - [1391, 760]
                  - [1415, 747]
                  - [1441, 736]
                  - [1469, 726]
                  - [1502, 717]
                  - [1527, 709]
                  - [1557, 697]
                  - [1584, 682]
                  - [1618, 661]
                  - [1665, 632]
                  - [1690, 616]
                  - [1731, 587]
                  - [1804, 541]
            - usage_percentage: 50
              path:
                  - [1365, 833]
                  - [1381, 852]
                  - [1401, 870]
                  - [1434, 899]
                  - [1449, 913]
                  - [1469, 929]
                  - [1493, 935]
                  - [1531, 943]
                  - [1559, 955]
                  - [1570, 964]
                  - [1586, 978]
                  - [1612, 1003]
                  - [1637, 1028]
                  - [1661, 1054]
                  - [1690, 1080]
                  - [1709, 1097]
                  - [1725, 1109]
                  - [1739, 1117]
                  - [1753, 1127]
                  - [1768, 1135]
                  - [1783, 1143]
                  - [1800, 1151]
                  - [1815, 1156]
                  - [1834, 1158]
                  - [1857, 1156]
                  - [1877, 1154]
                  - [1894, 1155]
                  - [1906, 1159]
                  - [1915, 1163]
                  - [1924, 1171]



  - name: to_east_es_outer_pedestrian
    path:
        - [360, 353]
        - [385, 352]
        - [407, 355]
        - [429, 366]
        - [457, 379]
        - [483, 393]
        - [513, 409]
        - [548, 426]
        - [582, 444]
        - [617, 461]
        - [657, 482]
        - [696, 501]
        - [731, 520]
        - [759, 533]
        - [792, 550]
        - [830, 570]
        - [860, 584]
        - [886, 599]
        - [913, 616]
        - [960, 646]
        - [1058, 718]
        - [1113, 757]
        - [1185, 812]
        - [1226, 845]
        - [1266, 874]
        - variations:
            - usage_percentage: 50
              path:
                  - [1263, 880]
                  - [1247, 892]
                  - [1234, 903]
                  - [1217, 914]
                  - [1201, 925]
                  - [1187, 935]
                  - [1181, 941]
                  - [1172, 948]
                  - [1166, 959]
                  - [1161, 970]
                  - [1156, 981]
                  - [1150, 991]
                  - [1133, 1004]
            - usage_percentage: 50
              path:
                  - [1283, 888]
                  - [1293, 897]
                  - [1304, 906]
                  - [1321, 913]
                  - [1332, 921]
                  - [1359, 945]
                  - [1378, 963]
                  - [1382, 972]
                  - [1397, 982]
                  - [1409, 994]
                  - [1415, 1000]
                  - [1422, 1005]
                  - [1425, 1011]
                  - [1429, 1025]
                  - [1429, 1046]
                  - [1428, 1067]
                  - [1427, 1086]
                  - [1425, 1103]
                  - [1420, 1119]
                  - [1410, 1139]





  - name: from_east_as_outer_pedestrian
    path:
        - variations:
            - usage_percentage: 50
              path:
                  - [1920, 1156]
                  - [1913, 1148]
                  - [1887, 1146]
                  - [1849, 1148]
                  - [1825, 1149]
                  - [1795, 1140]
                  - [1773, 1129]
                  - [1751, 1117]
                  - [1736, 1107]
                  - [1711, 1089]
                  - [1687, 1067]
                  - [1660, 1041]
                  - [1632, 1013]
                  - [1587, 969]
                  - [1567, 950]
                  - [1556, 943]
                  - [1534, 934]
                  - [1502, 931]
                  - [1481, 925]
                  - [1468, 922]
                  - [1457, 912]
                  - [1448, 904]
                  - [1413, 871]
                  - [1396, 855]
                  - [1382, 844]
                  - [1377, 836]
                  - [1369, 826]
                  - [1363, 818]
                  - [1345, 803]
            - usage_percentage: 50
              path:
                  - [1792, 536]
                  - [1779, 547]
                  - [1747, 569]
                  - [1706, 593]
                  - [1658, 622]
                  - [1607, 659]
                  - [1569, 681]
                  - [1523, 700]
                  - [1477, 716]
                  - [1441, 728]
                  - [1388, 752]
                  - [1364, 772]
                  - [1336, 796]
        - [1338, 792]
        - [1299, 758]
        - [1246, 713]
        - [1200, 672]
        - [1160, 639]
        - [1118, 607]
        - [1043, 553]
        - [991, 515]
        - [926, 476]
        - [875, 448]
        - [829, 421]
        - [780, 391]
        - [689, 340]
        - [586, 285]
        - [501, 241]
        - [458, 219]
        - [441, 205]
        - [432, 192]

  - name: from_east_es_outer_pedestrian
    path:
        - variations:
            - usage_percentage: 50
              path:
                  - [1417, 1137]
                  - [1421, 1129]
                  - [1428, 1117]
                  - [1430, 1106]
                  - [1432, 1094]
                  - [1434, 1074]
                  - [1435, 1059]
                  - [1435, 1038]
                  - [1434, 1017]
                  - [1426, 1001]
                  - [1375, 952]
                  - [1332, 915]
                  - [1314, 898]
                  - [1301, 888]
                  - [1271, 875]
            - usage_percentage: 50
              path:
                  - [1140, 1013]
                  - [1156, 996]
                  - [1167, 974]
                  - [1174, 959]
                  - [1185, 946]
                  - [1207, 930]
                  - [1227, 916]
                  - [1245, 900]
                  - [1257, 891]
                  - [1268, 883]
                  - [1272, 877]
        - [1265, 863]
        - [1191, 808]
        - [1121, 756]
        - [1083, 726]
        - [1044, 698]
        - [1018, 680]
        - [983, 654]
        - [942, 625]
        - [907, 603]
        - [857, 577]
        - [813, 553]
        - [758, 526]
        - [693, 492]
        - [557, 424]
        - [475, 382]
        - [426, 357]
        - [406, 349]
        - [387, 346]
        - [361, 347]













  - name: to_north_westside_crossing_pedestrian
    path:
        - [216, 251]
        - [242, 196]
        - [259, 164]
        - [278, 124]

  - name: to_south_westside_crossing_pedestrian
    path:
        - [261, 143]
        - [253, 161]
        - [247, 172]
        - [242, 181]
        - [236, 194]
        - [232, 204]
        - [228, 210]
        - [223, 223]
        - [212, 240]
        - [208, 248]


  - name: to_east_southside_crossing_pedestrian
    path:
        - [232, 297]
        - [243, 303]
        - [274, 318]
        - [329, 346]


  - name: to_west_southside_crossing_pedestrian
    path:
        - [331, 339]
        - [312, 330]
        - [301, 324]
        - [292, 320]
        - [279, 315]
        - [267, 308]
        - [254, 302]
        - [235, 293]


  - name: to_north_eastside_crossing_pedestrian
    path:
        - [368, 330]
        - [374, 314]
        - [390, 283]
        - [416, 228]

  - name: to_south_eastside_crossing_pedestrian
    path:
        - [414, 221]
        - [412, 228]
        - [388, 279]
        - [369, 314]
        - [359, 329]

  - name: to_east_northside_crossing_pedestrian
    path:
        - [303, 135]
        - [322, 142]
        - [342, 152]
        - [392, 175]

  - name: to_west_northside_crossing_pedestrian
    path:
        - [390, 170]
        - [356, 154]
        - [308, 132]