route_components:
  - name: to_east
    path:
        - [384, 304]
        - [410, 317]
        - [676, 452]
        - [856, 542]
        - [887, 557]
        - [927, 578]
        - [954, 592]
        - [984, 611]
        - [1006, 626]
        - [1053, 656]
        - [1095, 685]
        - [1137, 719]
        - [1175, 747]
        - [1195, 762]
        - to_east_outer
  - name: to_south
    path:
        - [259, 311]
        - [248, 331]
        - [242, 348]
        - [229, 368]
        - [216, 391]
        - [197, 425]
        - [181, 444]
        - [159, 470]
        - [132, 497]
        - [87, 538]
  - name: to_north
    path:
        - [369, 157]
        - [378, 141]
        - [392, 120]
        - [411, 85]
        - [449, 5]
        - [460, -10]
  - name: to_east_outer
    path:
        - [1231, 792]
        - [1267, 822]
        - [1304, 852]
        - [1348, 890]
        - [1386, 923]
        - [1432, 963]
        - [1462, 994]
        - [1479, 1021]
        - [1485, 1048]
        - [1493, 1071]
        - [1508, 1086]
        - [1539, 1091]
        - [1567, 1097]
        - [1599, 1114]
        - [1635, 1140]
        - [1658, 1160]
        - [1730, 1217]
  - name: to_west
    path:
        - [242, 168]
        - [216, 155]
        - [182, 137]
        - [127, 110]
        - [16, 55]
        - [0, 47]
        - [-33, 17]








  - name: to_north_outer_pedestrian
    path:
        - [300, 119]
        - [313, 111]
        - [326, 99]
        - [335, 84]
        - [351, 44]
        - [371, 2]
        - [374, -5]

  - name: to_north_crossing_pedestrian
    path:
        - [216, 251]
        - [242, 196]
        - [259, 164]
        - [278, 124]
