routes:
  # Vanuit zuid
  - name: from_south
    vehicle_type: car
    vehicles_per_minute: 10
    path:
      - variations:
          - usage_percentage: 30
            path:
              - [131, 543]
              - [152, 526]
              - [163, 500]
              - [186, 474]
              - [209, 446]
              - [228, 416]
              - [245, 390]
              - [258, 369]
              - [279, 328]
              - [299, 286]
              - [309, 262]
              - [311, 245]
              - [308, 227]
              - [304, 211]
              - [294, 197]
              - [280, 188]
              - to_west
          - usage_percentage: 30
            path:
              - [139, 540]
              - [161, 520]
              - [181, 498]
              - [201, 476]
              - [222, 450]
              - [233, 435]
              - [243, 419]
              - [252, 405]
              - [267, 379]
              - [278, 358]
              - [287, 341]
              - [297, 318]
              - [308, 295]
              - [318, 272]
              - [329, 248]
              - [338, 223]
              - [346, 204]
              - [353, 191]
              - to_north
          - usage_percentage: 30
            path:
              - [152, 548]
              - [176, 524]
              - [198, 500]
              - [222, 470]
              - [244, 440]
              - [263, 412]
              - [280, 380]
              - [300, 339]
              - [319, 307]
              - [330, 296]
              - [345, 290]
              - [359, 291]
              - to_east

  # Vanuit noord
  - name: from_north
    vehicle_type: car
    vehicles_per_minute: 50
    path:
      - variations:
          - usage_percentage: 30
            path:
              - [399, -21]
              - [391, 2]
              - [383, 20]
              - [372, 43]
              - [361, 64]
              - [353, 83]
              - [330, 131]
              - [322, 149]
              - [315, 160]
              - [305, 169]
              - [292, 175]
              - [266, 180]
              - to_west
          - usage_percentage: 30
            path:
              - [413, -13]
              - [399, 18]
              - [356, 106]
              - [337, 146]
              - [312, 195]
              - [299, 228]
              - [285, 260]
              - [274, 279]
              - to_south
          - usage_percentage: 40
            path:
              - [423, -10]
              - [413, 12]
              - [399, 43]
              - [371, 101]
              - [350, 141]
              - [330, 186]
              - [325, 201]
              - [319, 217]
              - [317, 235]
              - [318, 252]
              - [323, 265]
              - [328, 276]
              - [340, 282]
              - to_east

  # Vanuit oost
  - name: from_east
    vehicle_type: car
    vehicles_per_minute: 10
    path:
      - [1899, 1219]
      - [1884, 1205]
      - [1861, 1197]
      - [1837, 1199]
      - [1811, 1193]
      - [1770, 1177]
      - [1730, 1154]
      - [1688, 1123]
      - [1643, 1082]
      - [1549, 991]
      - [1532, 982]
      - [1517, 978]
      - [1500, 973]
      - [1486, 970]
      - [1469, 963]
      - [1455, 955]
      - [1350, 860]
      - [1295, 808]
      - [1238, 758]
      - [1189, 719]
      - [1105, 657]
      - [1035, 605]
      - [953, 550]
      - [890, 510]
      - variations:
          - usage_percentage: 10
            path:
                - [849, 484]
                - [810, 462]
                - [777, 444]
                - [743, 425]
                - [716, 410]
                - [696, 385]
                - [662, 365]
                - [632, 350]
                - [597, 331]
                - [423, 244]
                - [400, 232]
                - [382, 221]
                - [370, 206]
                - [364, 189]
                - [363, 167]
                - [374, 148]
                - [387, 127]
                - [402, 102]
                - [449, 6]
                - [457, -12]
                - to_north
          - usage_percentage: 70
            path:
                - multi_lane:
                    - path:
                        - [855, 489]
                        - [791, 452]
                        - [728, 417]
                        - [652, 375]
                        - [538, 314]
                        - [418, 254]
                        - [213, 155]
                        - [2, 50]
                        - [-22, 37]
                    - path:
                        - [852, 499]
                        - [826, 485]
                        - [799, 470]
                        - [757, 447]
                        - [721, 426]
                        - [667, 395]
                        - [553, 335]
                        - [412, 265]
                        - [209, 166]
                        - [13, 69]
                        - [-22, 51]
          - usage_percentage: 20
            path:
                - [852, 499]
                - [826, 485]
                - [799, 470]
                - [757, 447]
                - [721, 426]
                - [688, 421]
                - [658, 406]
                - [559, 355]
                - [407, 277]
                - [363, 255]
                - [339, 247]
                - [318, 245]
                - [296, 247]
                - [287, 256]
                - [278, 271]
                - [269, 286]
                - to_south


  # Vanuit west
  - name: from_west
    vehicle_type: car
    vehicles_per_minute: 50
    path:
      - variations:
          - usage_percentage: 20
            path:
                - [-25, 118]
                - [34, 146]
                - [156, 205]
                - [224, 239]
                - [248, 254]
                - [255, 263]
                - [260, 272]
                - [264, 280]
                - [266, 289]
                - [264, 298]
                - to_south
          - usage_percentage: 70
            path:
                - multi_lane:
                    - path:
                        - [-24, 91]
                        - [15, 108]
                        - [100, 149]
                        - [217, 208]
                        - [305, 250]
                        - [419, 308]
                        - [592, 394]
                        - [793, 496]
                        - [893, 546]
                        - [919, 558]
                        - [941, 569]
                        - [961, 582]
                        - [984, 596]
                        - [1022, 619]
                        - [1051, 638]
                        - [1089, 665]
                        - [1116, 685]
                        - [1145, 707]
                        - [1181, 735]
                    - path:
                        - [-13, 110]
                        - [20, 125]
                        - [57, 144]
                        - [163, 195]
                        - [327, 276]
                        - [557, 391]
                        - [765, 497]
                        - [889, 558]
                        - [921, 576]
                        - [955, 594]
                        - [985, 612]
                        - [1020, 634]
                        - [1053, 655]
                        - [1094, 685]
                        - [1131, 713]
                        - [1166, 739]
                        - [1197, 765]
                - to_east_outer
          - usage_percentage: 10
            path:
                - [-21, 76]
                - [9, 91]
                - [77, 125]
                - [190, 182]
                - [223, 197]
                - [252, 211]
                - [291, 230]
                - [310, 231]
                - [329, 224]
                - [341, 210]
                - [353, 190]
                - to_north



  # PEDESTRIAN

  # # Noord naar zuid
  # - vehicle_type: pedestrian
  #   vehicles_per_minute: 10
  #   path:
  #     - [581, -10]
  #     - [531, 85]
  #     - [505, 109]
  #     - [469, 120]
  #     - [449, 157] #
  #     - [428, 194] #
  #     - [398, 245]
  #     - [387, 265]
  #     - [401, 274]
  #     - [348, 392]
  #     - [315, 440]
  #     - [234, 512]

  # # West naar oost
  # - vehicle_type: pedestrian
  #   vehicles_per_minute: 10
  #   path:
  #     - [-25, 38]
  #     - [219, 173]
  #     - [385, 265]
  #     - [402, 278]
  #     - [399, 290]
  #     - [437, 311] #
  #     - [466, 325] #
  #     - [541, 366]
  #     - [562, 361]
  #     - [597, 364]
  #     - [629, 379]
  #     - [1089, 629]
  #     - [1242, 735]
  #     - [1352, 821]
  #     - [1471, 916]
  #     - [1562, 987]
  #     - [1655, 1066]
  #     - [1688, 1101]
  #     - [1691, 1118]
  #     - [1688, 1210]
