routes:
  # Vanuit zuid
  - name: from_south_car
    vehicle_type: car
    vehicles_per_interval_rustig: 15
    vehicles_per_interval_spits: 11
    path:
      - variations:
          - usage_percentage: 30
            associated_lane: "6.1"
            path:
              - [131, 543]
              - [152, 526]
              - [163, 500]
              - [186, 474]
              - [209, 446]
              - [228, 416]
              - [245, 390]
              - [258, 369]
              - [279, 328]
              - [299, 286]
              - [309, 262]
              - [311, 245]
              - [308, 227]
              - [304, 211]
              - [294, 197]
              - [280, 188]
              - to_west
          - usage_percentage: 30
            associated_lane: "5.1"
            path:
              - [139, 540]
              - [161, 520]
              - [181, 498]
              - [201, 476]
              - [222, 450]
              - [233, 435]
              - [243, 419]
              - [252, 405]
              - [267, 379]
              - [278, 358]
              - [287, 341]
              - [297, 318]
              - [308, 295]
              - [318, 272]
              - [329, 248]
              - [338, 223]
              - [346, 204]
              - [353, 191]
              - to_north
          - usage_percentage: 30
            associated_lane: "4.1"
            path:
              - [152, 548]
              - [176, 524]
              - [198, 500]
              - [222, 470]
              - [244, 440]
              - [263, 412]
              - [280, 380]
              - [300, 339]
              - [319, 307]
              - [330, 296]
              - [345, 290]
              - [359, 291]
              - to_east

  # Vanuit noord
  - name: from_north_car
    vehicle_type: car
    vehicles_per_interval_rustig: 20
    vehicles_per_interval_spits: 24
    path:
      - variations:
          - usage_percentage: 30
            associated_lane: "10.1"
            path:
              - [399, -21]
              - [391, 2]
              - [383, 20]
              - [372, 43]
              - [361, 64]
              - [353, 83]
              - [330, 131]
              - [322, 149]
              - [315, 160]
              - [305, 169]
              - [292, 175]
              - [266, 180]
              - to_west
          - usage_percentage: 30
            associated_lane: "11.1"
            path:
              - [413, -13]
              - [399, 18]
              - [356, 106]
              - [337, 146]
              - [312, 195]
              - [299, 228]
              - [285, 260]
              - [274, 279]
              - to_south
          - usage_percentage: 40
            associated_lane: "12.1"
            path:
              - [423, -10]
              - [413, 12]
              - [399, 43]
              - [371, 101]
              - [350, 141]
              - [330, 186]
              - [326, 202]
              - [325, 211]
              - [325, 219]
              - [328, 230]
              - [330, 242]
              - [334, 255]
              - [339, 271]
              - [344, 282]
              - [352, 288]
              - to_east

  # Vanuit oost
  - name: from_east_car
    vehicle_type: car
    vehicles_per_interval_rustig: 76
    vehicles_per_interval_spits: 103
    path:
      - [1899, 1219]
      - [1884, 1205]
      - [1861, 1197]
      - [1837, 1199]
      - [1811, 1193]
      - [1770, 1177]
      - [1730, 1154]
      - [1688, 1123]
      - [1643, 1082]
      - [1549, 991]
      - [1532, 982]
      - [1517, 978]
      - [1500, 973]
      - [1486, 970]
      - [1469, 963]
      - [1455, 955]
      - [1350, 860]
      - [1295, 808]
      - [1238, 758]
      - [1189, 719]
      - [1105, 657]
      - [1035, 605]
      - [953, 550]
      - [890, 510]
      - variations:
          - usage_percentage: 10
            associated_lane: "1.1"
            path:
                - [866, 494]
                - [828, 472]
                - [786, 449]
                - [749, 429]
                - [720, 411]
                - [709, 393]
                - [664, 366]
                - [581, 322]
                - [425, 244]
                - [386, 223]
                - [371, 208]
                - [368, 197]
                - [364, 180]
                - to_north
          - usage_percentage: 70
            path:
                - multi_lane:
                    - associated_lane: "2.1"
                      path:
                        - [855, 489]
                        - [791, 452]
                        - [728, 417]
                        - [652, 375]
                        - [538, 314]
                        - [418, 254]
                        - [213, 155]
                        - [2, 50]
                        - [-22, 37]
                    - associated_lane: "2.2"
                      path:
                        - [852, 499]
                        - [826, 485]
                        - [799, 470]
                        - [757, 447]
                        - [721, 426]
                        - [667, 395]
                        - [553, 335]
                        - [412, 265]
                        - [209, 166]
                        - [13, 69]
                        - [-22, 51]
          - usage_percentage: 20
            associated_lane: "3.1"
            path:
                - [852, 499]
                - [826, 485]
                - [799, 470]
                - [757, 447]
                - [721, 426]
                - [688, 421]
                - [658, 406]
                - [559, 355]
                - [407, 277]
                - [363, 255]
                - [339, 247]
                - [318, 245]
                - [296, 247]
                - [287, 256]
                - [278, 271]
                - [269, 286]
                - to_south


  # Vanuit west
  - name: from_west_car
    vehicle_type: car
    vehicles_per_interval_rustig: 79
    vehicles_per_interval_spits: 77
    path:
      - variations:
          - usage_percentage: 20
            associated_lane: "7.1"
            path:
                - [-25, 118]
                - [34, 146]
                - [156, 205]
                - [224, 239]
                - [248, 254]
                - [255, 263]
                - [260, 272]
                - [264, 280]
                - [266, 289]
                - [264, 298]
                - to_south
          - usage_percentage: 70
            path:
                - multi_lane:
                    - associated_lane: "8.2"
                      path:
                        - [-24, 91]
                        - [15, 108]
                        - [100, 149]
                        - [217, 208]
                        - [305, 250]
                        - [419, 308]
                        - [592, 394]
                        - [793, 496]
                        - [893, 546]
                        - [919, 558]
                        - [941, 569]
                        - [961, 582]
                        - [984, 596]
                        - [1022, 619]
                        - [1051, 638]
                        - [1089, 665]
                        - [1116, 685]
                        - [1145, 707]
                        - [1181, 735]
                    - associated_lane: "8.1"
                      path:
                        - [-13, 110]
                        - [20, 125]
                        - [57, 144]
                        - [163, 195]
                        - [327, 276]
                        - [557, 391]
                        - [765, 497]
                        - [889, 558]
                        - [921, 576]
                        - [955, 594]
                        - [985, 612]
                        - [1020, 634]
                        - [1053, 655]
                        - [1094, 685]
                        - [1131, 713]
                        - [1166, 739]
                        - [1197, 765]
                - to_east_outer
          - usage_percentage: 10
            associated_lane: "9.1"
            path:
                - [-21, 76]
                - [9, 91]
                - [77, 125]
                - [190, 182]
                - [223, 197]
                - [252, 211]
                - [291, 230]
                - [310, 231]
                - [329, 224]
                - [341, 210]
                - [353, 190]
                - to_north



  # PEDESTRIAN
  - name: from_west_as_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_west_as_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_north_westside_crossing_pedestrian
              - to_north_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_east_southside_crossing_pedestrian
              - to_east_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_south_es_outer_pedestrian

  - name: from_west_es_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_west_es_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_south_westside_crossing_pedestrian
              - to_south_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_east_northside_crossing_pedestrian
              - to_east_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_north_as_outer_pedestrian

  - name: from_north_as_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_north_as_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_south_westside_crossing_pedestrian
              - to_south_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_east_northside_crossing_pedestrian
              - to_east_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_west_es_outer_pedestrian

  - name: from_north_es_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_north_es_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_south_eastside_crossing_pedestrian
              - to_south_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_west_northside_crossing_pedestrian
              - to_west_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_east_as_outer_pedestrian

  - name: from_south_as_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_south_as_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_north_eastside_crossing_pedestrian
              - to_north_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_west_southside_crossing_pedestrian
              - to_west_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_east_es_outer_pedestrian

  - name: from_south_es_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_south_es_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_north_westside_crossing_pedestrian
              - to_north_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_east_southside_crossing_pedestrian
              - to_east_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_west_as_outer_pedestrian

  - name: from_east_as_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_east_as_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_south_eastside_crossing_pedestrian
              - to_south_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_west_northside_crossing_pedestrian
              - to_west_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_north_es_outer_pedestrian

  - name: from_east_es_pedestrian
    vehicle_type: pedestrian
    vehicles_per_interval_rustig: 3
    vehicles_per_interval_spits: 1
    path:
      - from_east_es_outer_pedestrian
      - variations:
          - usage_percentage: 33
            path:
              - to_north_eastside_crossing_pedestrian
              - to_north_es_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_west_southside_crossing_pedestrian
              - to_west_as_outer_pedestrian
          - usage_percentage: 33
            path:
              - to_south_as_outer_pedestrian



  # BOAT
  - name: from_north_boat
    vehicle_type: boat
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 0
    path:
      - [1952, 533]
      - [1854, 607]
      - [1747, 674]
      - [1583, 776]
      - [1533, 805]
      - [1530, 808]
      - [1528, 811]
      - [1526, 814]
      - [1524, 816]
      - [1522, 819]
      - [1520, 822]
      - [1517, 825]
      - [1515, 828]
      - [1496, 842]
      - [1446, 871]
      - [1329, 947]
      - [1323, 950]
      - [1318, 952]
      - [1312, 954]
      - [1304, 957]
      - [1296, 961]
      - [1255, 983]
      - [1195, 1022]
      - [1159, 1048]

  - name: from_south_boat
    vehicle_type: boat
    vehicles_per_interval_rustig: 1
    vehicles_per_interval_spits: 0
    path:
      - [1184, 1064]
      - [1272, 1012]
      - [1276, 1010]
      - [1279, 1006]
      - [1282, 1001]
      - [1284, 996]
      - [1286, 990]
      - [1288, 985]
      - [1290, 981]
      - [1292, 978]
      - [1295, 974]
      - [1298, 970]
      - [1303, 965]
      - [1309, 961]
      - [1352, 934]
      - [1430, 884]
      - [1452, 869]
      - [1457, 866]
      - [1462, 863]
      - [1466, 861]
      - [1470, 859]
      - [1474, 858]
      - [1478, 857]
      - [1482, 856]
      - [1487, 855]
      - [1492, 855]
      - [1497, 854]
      - [1502, 853]
      - [1544, 827]
      - [1710, 722]
      - [1885, 616]
      - [1952, 589]



  # BIKE
  - name: from_west_as_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_west_as_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_north_westside_crossing_bike
              - to_east_northside_crossing_bike
              - to_north_outer_bike
          - usage_percentage: 33
            path:
              - to_east_southside_crossing_bike
              - to_east_es_outer_bike
          - usage_percentage: 33
            path:
              - to_south_es_outer_bike

  - name: from_west_es_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_west_es_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_south_westside_crossing_bike
              - to_south_es_outer_bike
          - usage_percentage: 33
            path:
              - to_east_northside_crossing_bike
              - to_east_as_outer_bike
          - usage_percentage: 33
            path:
              - to_east_northside_crossing_bike
              - to_north_outer_bike

  - name: from_north_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_north_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_south_westside_crossing_bike
              - to_south_es_outer_bike
          - usage_percentage: 33
            path:
              - to_east_northside_crossing_bike
              - to_east_as_outer_bike
          - usage_percentage: 33
            path:
              - to_west_es_outer_bike

  - name: from_south_as_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_south_as_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_north_eastside_crossing_bike
              - to_north_outer_bike
          - usage_percentage: 33
            path:
              - to_west_southside_crossing_bike
              - to_west_as_outer_bike
          - usage_percentage: 33
            path:
              - to_east_es_outer_bike

  - name: from_south_es_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_south_es_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_north_westside_crossing_bike
              - to_east_northside_crossing_bike
              - to_north_outer_bike
          - usage_percentage: 33
            path:
              - to_east_southside_crossing_bike
              - to_east_es_outer_bike
          - usage_percentage: 33
            path:
              - to_west_as_outer_bike

  - name: from_east_as_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_east_as_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_south_eastside_crossing_bike
              - to_south_as_outer_bike
          - usage_percentage: 33
            path:
              - to_west_northside_crossing_bike
              - to_west_es_outer_bike
          - usage_percentage: 33
            path:
              - to_north_outer_bike

  - name: from_east_es_bike
    vehicle_type: bike
    vehicles_per_interval_rustig: 2
    vehicles_per_interval_spits: 1
    path:
      - from_east_es_outer_bike
      - variations:
          - usage_percentage: 33
            path:
              - to_north_eastside_crossing_bike
              - to_north_outer_bike
          - usage_percentage: 33
            path:
              - to_west_southside_crossing_bike
              - to_west_as_outer_bike
          - usage_percentage: 33
            path:
              - to_south_as_outer_bike