special_sensors:
  - name: brug_wegdek
    position: [1395, 909]
    dimensions: [130, 50]
    vehicle_types: [car, pedestrian, bike]
  - name: brug_water
    position: [1404, 907]
    dimensions: [232, 210]
    vehicle_types: [boat]
  - name: brug_file
    position: [679, 445]
    dimensions: [24, 24]
    vehicle_types: [car]